# What is Numpy?


Numpy is the fundamental package for scientific computing in python.It is a python library that
provides a multidimensional array object, various dervied objects(such as masked arrays and
matrices), and an assortment of routines for fast operations on arrays, including mathematical,
logical,shape manipulation,sorting,selecting,I/O,discrete Fourier transforms,basics linear algebra
,basic statistical operation,random simulation and much more.
 At the core of the NUmpy package, is the ndarray object.This encapsulates arrays of homogeneous
 data types.


# NUMPY ARRAYS VS PYTHON SEQUENCES

- Numpy arrays have a fixed size at creation, unlike python lists(which can grow dynamically).
changing the size of an ndarray will create a new array and delete the original.
- The elements in a Numpy array are all required to be the same data type,and thus will be the same
size in memory.
- Numpy arrays facilites advanced mathematical and other types of operations on large number of
data .Typically ,such operations are executed more efficient and with less code than is possible
using python built-in sequence.
- A growing plethora of scientific and mathematical python-based package are using Numpy arrays.
though these typically support python-sequence input;they convert such input  to NUMpy arrays prior
to processing , and they often output Numpy arrays.

# Creating Numpy Arrays

In [2]:
# np.array/ 1D array
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 3D array
c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
# dtype/change into anything like float,bool
a = np.array([1, 2, 3], dtype=bool)
a

array([ True,  True,  True])

In [6]:
b = np.array([1, 2, 3], dtype=float)
a

array([ True,  True,  True])

In [7]:
b = np.array([1, 2, 3], dtype=complex)
b

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
# np.arange
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
b = np.arange(1, 11, 2)
b

array([1, 3, 5, 7, 9])

In [10]:
# with reshape/ To shape 3*3 matrics
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# np.ones/ in tuples
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# np.zeros
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# np.random
c = np.random.random((3, 3))
c

array([[0.06125705, 0.79316744, 0.47311374],
       [0.69853158, 0.50927609, 0.02315448],
       [0.93972343, 0.26669811, 0.15177269]])

In [14]:
# np.linspace
a = np.linspace(-10, 10, 10)
a

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
a = np.linspace(-10, 10, 10, dtype=int)
a

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [16]:
# np.identify
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [17]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
# ndim
a3.ndim

3

In [19]:
# size
a2.size

12

In [20]:
# itemsize
a3.itemsize

8

In [21]:
# dtype
a1.dtype
a2.dtype
a3.dtype

dtype('int64')

### Changing Datatype

In [22]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operation

In [23]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)
print(a1)
a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
# Scalar operation

#  ALL Arithmetic are allow like + - * / // %
print(a1 * 2)
a2 * 2

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [25]:
# relational
print(a1 > 15)
print()
print(a1 > 4)
a1 == 10

[[False False False False]
 [False False False False]
 [False False False False]]

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [26]:
# vector operations
# arithmetic are allow like + - * / // %
print(a1)
print()
print(a2)
print()
a1 + a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Function

In [28]:
a1 = np.random.random((3, 3))
a1 = np.round(a1 * 100)
a1

array([[ 41., 100.,  21.],
       [ 47.,  28.,  25.],
       [ 29.,  18.,  21.]])

In [31]:
# max/min/sum/product(prod)
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
np.prod(a1)

100.0
18.0
330.0


np.float64(31051947780000.0)

In [37]:
# max/min/sum/product(prod)
# 0-> coloum and 1-> Row
print(np.max(a1, axis=1))
print(np.max(a1, axis=0))
print(np.sum(a1, axis=1))
print(np.sum(a1, axis=0))

[100.  47.  29.]
[ 47. 100.  25.]
[162. 100.  68.]
[117. 146.  67.]


In [42]:
# mean/median/std/var
print(np.mean(a1))
print(np.mean(a1, axis=1))  # row wise mean value
print(np.median(a1))
print(np.std(a1))
np.var(a1)

36.666666666666664
[54.         33.33333333 22.66666667]
28.0
24.143091949642425


np.float64(582.8888888888889)

In [44]:
# trigonomoetic functions
np.sin(a1)

array([[-0.15862267, -0.50636564,  0.83665564],
       [ 0.12357312,  0.27090579, -0.13235175],
       [-0.66363388, -0.75098725,  0.83665564]])

In [48]:
# dot product
a2 = np.arange(12).reshape(3, 4)
print(a2)
print()
a3 = np.arange(12, 24).reshape(4, 3)
print(a3)
print()
print(np.dot(a2, a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [50]:
# log and exponents
print(np.log(a1))
np.exp(a1)

[[3.71357207 4.60517019 3.04452244]
 [3.8501476  3.33220451 3.21887582]
 [3.36729583 2.89037176 3.04452244]]


array([[6.39843494e+17, 2.68811714e+43, 1.31881573e+09],
       [2.58131289e+20, 1.44625706e+12, 7.20048993e+10],
       [3.93133430e+12, 6.56599691e+07, 1.31881573e+09]])

In [54]:
# round/floor/ceil
np.round(np.random.random((2, 3)) * 100)
np.floor(np.random.random((2, 3)) * 100)
np.ceil(np.random.random((2, 3)) * 100)

array([[52., 13., 25.],
       [ 7., 86., 96.]])

### Indexing and slicing

In [56]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)
print(a1)  # 1D
print()
print(a2)  # 2D
print()
a3  # 3D

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1[-1]

np.int64(9)

In [61]:
a1[0]

np.int64(0)

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a2[1, 2]  # 1 for row and 2 for coloum

np.int64(6)

In [65]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [67]:
a3[1, 0, 1]  # 1 for pehla box ya dursa

np.int64(5)

### Slicing

In [68]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a1[2:5]

array([2, 3, 4])

In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2[0, :]

array([0, 1, 2, 3])

In [73]:
a2[:, 2]

array([ 2,  6, 10])

In [ ]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [75]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [76]:
a3 = np.arange(27).reshape(3, 3, 3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [77]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [78]:
a3[::3]

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [83]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
a3[0, 1, :]

array([3, 4, 5])

### Iterating

In [85]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [88]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [91]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [93]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [94]:
# reshape

In [98]:
# Transpose
print(a2)
print()
print(np.transpose(a2))
print()
# short-cut
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [100]:
# ravel-convert into 1D
print(a2)
print()
print(a2.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stacking

In [104]:
# Horizontal stacking
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)
print(a4)
print()
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [107]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [108]:
# Vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Spliting

In [109]:
# Horizontal spliting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [111]:
# Vertical spliting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]