### np.sort

- Return a sorted copy of an array

In [2]:
# code
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [3]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[68,  7, 62, 24],
       [98, 73, 72, 77],
       [69, 31, 97,  8],
       [ 5, 33, 39, 85],
       [61, 56, 31, 48],
       [51, 68, 10, 71]], dtype=int32)

In [4]:
np.sort(a)  # sorted in ascending order

array([ 3,  9, 10, 11, 16, 38, 40, 44, 65, 68, 76, 84, 87, 88, 90],
      dtype=int32)

In [5]:
np.sort(a)[::-1]  # sorted in descending order

array([90, 88, 87, 84, 76, 68, 65, 44, 40, 38, 16, 11, 10,  9,  3],
      dtype=int32)

In [6]:
np.sort(b)  # ascending order in row wise

array([[ 7, 24, 62, 68],
       [72, 73, 77, 98],
       [ 8, 31, 69, 97],
       [ 5, 33, 39, 85],
       [31, 48, 56, 61],
       [10, 51, 68, 71]], dtype=int32)

In [7]:
np.sort(b, axis=0)  # descending order in coloum wise

array([[ 5,  7, 10,  8],
       [51, 31, 31, 24],
       [61, 33, 39, 48],
       [68, 56, 62, 71],
       [69, 68, 72, 77],
       [98, 73, 97, 85]], dtype=int32)

### np.append()

- The numpy.append() appends values along the mentioned axis at the end of the array

In [8]:
# code
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [9]:
np.append(a, 200)

array([ 11,  88,  44,  68,   9,  65,  87,  76,   3,  90,  16,  84,  40,
        10,  38, 200])

In [10]:
b

array([[68,  7, 62, 24],
       [98, 73, 72, 77],
       [69, 31, 97,  8],
       [ 5, 33, 39, 85],
       [61, 56, 31, 48],
       [51, 68, 10, 71]], dtype=int32)

In [11]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[68.,  7., 62., 24.,  1.],
       [98., 73., 72., 77.,  1.],
       [69., 31., 97.,  8.,  1.],
       [ 5., 33., 39., 85.,  1.],
       [61., 56., 31., 48.,  1.],
       [51., 68., 10., 71.,  1.]])

### np.concatenate

- numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [12]:
# code
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)
print(c)
print()
print(d)


[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c, d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

- with the help np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [14]:
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [15]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

- with help of Numpy.expand_dims() method,we can get the expanded dimensions of an array

In [16]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [18]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [19]:
np.expand_dims(a, axis=1).shape

(15, 1)

### np.where

- The numpy.where() function returns the indicates of elements in an input array where the given condition is satisfied.

In [20]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [21]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 1,  3,  5,  6,  7,  9, 11]),)

In [23]:
# replace all values > 50 with 0
np.where(a > 50, 0, a)

array([11,  0, 44,  0,  9,  0,  0,  0,  3,  0, 16,  0, 40, 10, 38],
      dtype=int32)

In [24]:
# replace even number > 50 with 0
np.where(a % 2 == 0, 0, a)

array([11,  0,  0,  0,  9, 65, 87,  0,  3,  0,  0,  0,  0,  0,  0],
      dtype=int32)

### np.argmax and argmin

- The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [25]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [26]:
np.argmax(a)

np.int64(9)

In [27]:
np.argmin(a)

np.int64(8)

In [28]:
b

array([[68,  7, 62, 24],
       [98, 73, 72, 77],
       [69, 31, 97,  8],
       [ 5, 33, 39, 85],
       [61, 56, 31, 48],
       [51, 68, 10, 71]], dtype=int32)

In [29]:
np.argmax(b, axis=0)

array([1, 1, 2, 3])

In [30]:
np.argmin(b, axis=0)

array([3, 0, 5, 2])

### np.cumsum and np.cumprod

- numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [31]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [32]:
np.cumsum(a)

array([ 11,  99, 143, 211, 220, 285, 372, 448, 451, 541, 557, 641, 681,
       691, 729])

In [33]:
b

array([[68,  7, 62, 24],
       [98, 73, 72, 77],
       [69, 31, 97,  8],
       [ 5, 33, 39, 85],
       [61, 56, 31, 48],
       [51, 68, 10, 71]], dtype=int32)

In [34]:
np.cumsum(b)

array([  68,   75,  137,  161,  259,  332,  404,  481,  550,  581,  678,
        686,  691,  724,  763,  848,  909,  965,  996, 1044, 1095, 1163,
       1173, 1244])

In [35]:
np.cumsum(b, axis=0)

array([[ 68,   7,  62,  24],
       [166,  80, 134, 101],
       [235, 111, 231, 109],
       [240, 144, 270, 194],
       [301, 200, 301, 242],
       [352, 268, 311, 313]])

In [36]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [37]:
np.cumprod(a)

array([                  11,                  968,                42592,
                    2896256,             26066304,           1694309760,
               147404949120,       11202776133120,       33608328399360,
           3024749555942400,    48395992895078400,  4065263403186585600,
       -3410160535922540544,  2791882788193697792, -4588918490896793600])

In [38]:
np.cumprod(b)

array([                  68,                  476,                29512,
                     708288,             69412224,           5067092352,
               364830649344,       28091959999488,     1938345239964672,
          60088702438904832,  5828604136573768704, -8711399128538505216,
       -6663507495273422848,  1465181540491665408,  1801847858046296064,
        5583115344258752512,  8528642673011974144, -2011356227777789952,
       -7011810839982833664, -4525526992404086784,  9005796345615745024,
        3651597069455458304,  -377517452864520192, -8356995079671382016])

### np.percentile

- numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [39]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [ ]:
np.percentile(a, 100) # max value

np.float64(90.0)

In [ ]:
np.percentile(a, 0) # min vaule

np.float64(3.0)

In [ ]:
np.percentile(a, 50) # median value

np.float64(44.0)

### np.histogram

- Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [43]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [44]:
np.histogram(a, bins=[0, 50, 100])

(array([8, 7]), array([  0,  50, 100]))

### np.corrcoef

- Return Pearson product-moment correlation coefficients.

In [45]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

- with the help of numpy.isin()method,we can see that one array having values are checked in a different numpy array having
different elements with different size.

In [47]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [48]:
items = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
np.isin(a, items)

array([False, False, False, False, False, False, False, False, False,
        True, False, False,  True,  True, False])

In [49]:
a[np.isin(a, items)]

array([90, 40, 10], dtype=int32)

### np.flip

- The numpy.flip() function reverse the order of array elements along the specified axis,preserving the shape of the array.

In [50]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [51]:
np.flip(a)

array([38, 10, 40, 84, 16, 90,  3, 76, 87, 65,  9, 68, 44, 88, 11],
      dtype=int32)

In [52]:
b

array([[68,  7, 62, 24],
       [98, 73, 72, 77],
       [69, 31, 97,  8],
       [ 5, 33, 39, 85],
       [61, 56, 31, 48],
       [51, 68, 10, 71]], dtype=int32)

In [53]:
np.flip(b)

array([[71, 10, 68, 51],
       [48, 31, 56, 61],
       [85, 39, 33,  5],
       [ 8, 97, 31, 69],
       [77, 72, 73, 98],
       [24, 62,  7, 68]], dtype=int32)

### np.put

- The numpy.put() function replaces specific elements of an array with given value of p_array.Array indexed works on flattened
array.

In [54]:
a

array([11, 88, 44, 68,  9, 65, 87, 76,  3, 90, 16, 84, 40, 10, 38],
      dtype=int32)

In [ ]:
np.put(a, [0, 1], [110, 530]) # this method should permanent change print again

In [57]:
a

array([110, 530,  44,  68,   9,  65,  87,  76,   3,  90,  16,  84,  40,
        10,  38], dtype=int32)

### np.delete

- The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [58]:
a

array([110, 530,  44,  68,   9,  65,  87,  76,   3,  90,  16,  84,  40,
        10,  38], dtype=int32)

In [59]:
np.delete(a, 0)

array([530,  44,  68,   9,  65,  87,  76,   3,  90,  16,  84,  40,  10,
        38], dtype=int32)

In [60]:
np.delete(a, [0, 4, 5])

array([530,  44,  68,  87,  76,   3,  90,  16,  84,  40,  10,  38],
      dtype=int32)

### Set Functions


- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [61]:
m = np.array([1, 2, 3, 4, 5])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
np.intersect1d(m, n)

array([3, 4, 5])

In [64]:
np.setdiff1d(m, n)

array([1, 2])

In [65]:
np.setxor1d(m, n)

array([1, 2, 6, 7])

In [66]:
np.in1d(m, 10)

C:\Users\pramo\AppData\Local\Temp\ipykernel_16424\1640649773.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m, 10)


array([False, False, False, False, False])